### ISSUE TITLE
bit timing is invalid in kvaser

### ISSUE THREAD

**Issue by zhikangfan01** [hardbyte/python-can#1432]
I used kvaser to customize the baud rate and found that the tseg values obtained in kwargs are all 0

python-can version:V4.0

This is not the case with v3.3.4

![image](https://user-images.githubusercontent.com/118244230/201834762-39e08285-7b41-46eb-b9bd-89561aae1b4c.png)

Could you please check the problem? Or could you please provide a reference code? Thank you

**Comment by zariiii9003** [comment]
Could you print `kwargs`?

**Comment by zariiii9003** [comment]
I guess the problem is here:
https://github.com/hardbyte/python-can/blob/2e2f157eb02c0505c4e38ca8cbbc54433c65351c/can/util.py#L250

Your timings are replaced with a `can.BitTiming` object, but most interfaces do not support that.

@christiansandberg Could you take a look here? Are there any downsides to keeping tseg1 etc. in the config?

**Comment by zhikangfan01** [comment]
May I ask what content to modify to support the current use

**Comment by zariiii9003** [comment]
You could instantiate KvaserBus directly 
```
from can.interfaces.kvaser import KvaserBus

bus = KvaserBus(channel=0, ...)
```

**Comment by zhikangfan01** [comment]
Use the method you provided first to find or not to use@zariiii9003 
![image](https://user-images.githubusercontent.com/118244230/204754711-5349d52e-3b34-4821-a9fd-d1091d4f0817.png)
