### ISSUE TITLE
Stay alive while there is work to do

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#3]
Originally reported by: **Brian Thorne (Bitbucket: [hardbyte](https://bitbucket.org/hardbyte), GitHub: [hardbyte](https://github.com/hardbyte))**

---

The transmit threads don't prevent the Python interpreter from shutting down - which if they have out bound messages in their queue means messages won't get transmitted.

A simple but horrible solution is to wait or sleep after sending in a short program. A better solution would be great.

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/3

**Comment by felixdivo** [comment]
At least `Notifier.stop()` blocks until all listeners receive the last message and return. 

But in order to realize the completion of pending send requests, we would have to implement it with a separate thread and a message queue. The `bus.shutdown()` method then closes the queue (does not allow new messages to be added) and processes the remaining messages and blocks until that finished. At least that's my point of view.

**Comment by felixdivo** [comment]
As I see it, that already works ... 

1. Sending messages should work, since the `send()` method blocks until the message has been sent.

2. And about receiving messages: When using the `recv()` method directly, that is not a problem. But when a `Notifier` is used, this should work as well since the call to `stop()` clearly marks the end of the `recv()` loop. And it blocks until all listeners receive the last message and return.
