### ISSUE TITLE
Importing tries to load SocketCAN on Windows

### ISSUE THREAD

**Issue by tpwrules** [hardbyte/python-can#349]
I just upgraded to 2.2.0. Now when I do `import can` on Windows, I get the following logging messages:
```
fcntl not available on this platform
libc is unavailable
```
This appears to be the result of trying to load SocketCAN, but that will never work on Windows and the error messages clutter up my program. These messages were not printed in 2.1.0.

**Comment by christiansandberg** [comment]
Hmm right, it's because we've had `can.interface.CyclicSendTask` and `can.interface.MultiRateCyclicSendTask` that are SocketCAN only. Is anybody actually using these? I'm guessing it wouldn't be a big deal if we removed it. It's not really documented either. Just a commented out section in one of the examples with a note:

> Will have to consider how to expose items like this. The socketcan interfaces will continue to support it... but the top level api won't.

**Comment by hardbyte** [comment]
Thanks for reporting Thomas. Yeah I think we can make a bugfix release for this.
