### ISSUE TITLE
Vector unconnected interface handling

### ISSUE THREAD

**Issue by tpwrules** [hardbyte/python-can#353]
https://github.com/hardbyte/python-can/blob/6d0f4a66d121e86d2c8c707ce11546822a0ca1d2/can/interfaces/vector/canlib.py#L102-L104

If the application config is okay but the interface that channel is associated to is disconnected, xlGetChannelIndex returns a negative number and `mask = 1 << idx` fails with `ValueError: negative shift count`.

In 2.1.0, it died here: https://github.com/hardbyte/python-can/blob/338d21191ef89e9cb515eae80d9d945d12028477/can/interfaces/vector/canlib.py#L83-L85
with `can.interfaces.vector.exceptions.VectorError: XL_ERR_WRONG_PARAMETER`, presumably as a result of passing the negative self.mask to the Vector API.

Neither is a particularly graceful way of handling the error. Does their API documentation say what's supposed to happen when the interface isn't there? Is it possible to test that and raise a nicer exception?

**Comment by tpwrules** [comment]
Did a little more research and the manual is light on details but it seems `vxlapi.h` clarifies this: https://github.com/parai/as/blob/4f13992efe1451027f2b6bd88e6e4f3374325b01/com/as.virtual/include/vxlapi.h#L3693-L3695

Perhaps in that case the return should be converted into `XL_ERR_HW_NOT_PRESENT`?

**Comment by Panda-Engineer** [comment]
Dear all,

I have a similier error. Currently I use Vector 1640 with CANoe measure can-bus data correctly. all channel are well connected to CANoe. But I running my algorithm came up with error, following is my code and error information.
# code :
### import can
### bus = can.interface.Bus(bustype='vector', app_name=None, channel=0, bitrate=500000)
# error:
Traceback (most recent call last):

  File "C:\Users\.spyder-py3\temp.py", line 10, in <module>
  bus = can.interface.Bus(bustype = 'vector', app_name = None, channel = 0, bitrate = 500000)

  File "C:\Users\anaconda3\lib\site-packages\can\interface.py", line 127, in __new__
    return cls(channel, *args, **kwargs)

  File "C:\Users\anaconda3\lib\site-packages\can\interfaces\vector\canlib.py", line 156, in __init__
   vxlapi.XL_INTERFACE_VERSION, vxlapi.XL_BUS_TYPE_CAN)

  File "C:\Users\anaconda3\lib\site-packages\can\interfaces\vector\vxlapi.py", line 206, in check_status
    raise VectorError(result, xlGetErrorString(result).decode(), function.__name__)

### VectorError: xlOpenPort failed (XL_ERR_INVALID_CHANNEL_MASK)
# support:
I try to debug the code deeply, but I can't find where is the root cause.

if you could give me some hint or suggestion could be much more benefit for my work.

Thanks in advance.:smile:  :thumbsup:

**Comment by christiansandberg** [comment]
Try setting app_name to "CANoe".
