### ISSUE TITLE
Release 3.3.2 not in PyPI

### ISSUE THREAD

**Issue by jluttine** [hardbyte/python-can#698]
I noticed there's a release 3.3.2: https://github.com/hardbyte/python-can/releases/tag/3.3.2

But currently the most recent version in PyPI is 3.3.1: https://pypi.org/project/python-can/

Could you release also in PyPI?

**Comment by aquatsr** [comment]
Maybe pypi rejected it because the version still says `3.2.0` ?
```
~/Downloads/python-can-3.3.2$ grep -ir "__VERSION__" .
./can/__init__.py:__version__ = "3.2.0"
```

**Comment by hardbyte** [comment]
@jluttine thanks for pointing this out - looks like I tagged the develop branch instead of master. I've just re-tagged and creating a new release in GitHub, 🤞 travis-ci should be building and uploading to PyPi soon.

@aquatsr you can see the latest `__init__.py` in master has the correct version: https://github.com/hardbyte/python-can/blob/master/can/__init__.py#L11

**Comment by hardbyte** [comment]
v3.3.2 is now available in PyPi - https://pypi.org/project/python-can/3.3.2/
