### ISSUE TITLE
sharing virtualCAN network interface between docker container

### ISSUE THREAD

**Issue by ironWolf1990** [hardbyte/python-can#873]
How can add share a vcan network created on my host pc with a docker container?

**Comment by karlding** [comment]
Not sure if this is necessarily the best place to get a response, since this doesn't seem specific to `python-can`&mdash;you might get better responses on the SocketCAN mailing lists or the Docker/container runtime Slack/community/StackOverflow.

However, I'll take a stab at this and perhaps provide some thoughts which you might find useful.

I would expect that you could simply use `--network=host`, which will expose all the host's interfaces. If the idea is that you are running untrusted containers (or this is part of your threat model), then I suppose this doesn't work for your use case.

The net subsystem (and in particular, the `vcan` drivers) _does_ support network namespaces ever since the Linux 4.12 kernel though, so you should just be able to use the same namespace as the one the container is running under. I am not overly familiar with Docker, but I'd expect that the same principles behind kernel namespaces would apply here (since I don't think Docker and the runtime provide anything extra in this case over plain cgroups/namespaces). You shouldn't even need privileged mode&mdash;the idea is that you'd create an interface under a specific namespace and then expose it to your container.

For example, something like the following _should_ work (borrowing slightly from this [script](https://gist.github.com/brendangregg/1abcfeef9155ac526197f6f0abdd86bf) by Brendan Gregg of Linux tracing fame):

```bash
# Host: Find the running container ID, which we'll use to access the container's namespace
docker ps
# If you just have one container running, then it'll be equal to
# container_id=$(docker ps -q)
# Otherwise, find the UUID of your running container
# container_id=fccdd97372e1

# Host: Get the PID of the currently running container
pid=$(docker inspect -f '{{.State.Pid}}' ${container_id})
# Host: Expose the namespace that the process is running under
ln -sfT /proc/${pid}/ns/net /var/run/netns/${container_id}

# Host: Create a new interface under that namespace
ip netns exec ${container_id} ip link add dev vcan0 type vcan
ip netns exec ${container_id} ip link set up vcan0

# Host: Run cangen under the namespace
ip netns exec ${container_id} cangen vcan0

# Container: Access the interface, which is visible since we're in the same namespace
candump vcan0
```

You can convince yourself that these are truly separate namespaces by creating a separate `vcan0` in the default network namespace on your host and running `candump`/`cangen` on that. Similarly, you can move interfaces to the namespace if desired.

I suppose there's also the `vxcan` driver if you want to tunnel (ie. exchange between namespaces or the root namespace), which should act in basically the same way as the other virtual network drivers. You might find [this discussion](https://www.spinics.net/lists/linux-can/msg00297.html) about containers, vxcan and cangw from the Linux-CAN mailing list helpful.
