### ISSUE TITLE
Error during continuous recording for 300s by RPI and seeed-CAN-Bus

### ISSUE THREAD

**Issue by qdzpx123** [hardbyte/python-can#959]
Hi all,
I use RPI and CAN bus record 2 channels CAN frame.
When logger time about 305s,the CAN decoder data will not right.It looks like the timestap is not right.
However,If I only recoder 1 channel,the CAN decoder data will be exactly all time.

Hardware:
raspberry 3B
seeed CAN

test code:

```
import time
import can
import os
os.system("sudo /sbin/ip link set can0 up type can bitrate 500000")
os.system("sudo /sbin/ip link set can1 up type can bitrate 500000")
#os.system('sudo ifconfig can0 txqueuelen 65536')
#os.system('sudo ifconfig can1 txqueuelen 65536')
bus = can.interface.Bus(channel='',bustype = 'socketcan')
while True:
    message = bus.recv(1)
    if message is None:
        print('\n','Timeout occured, no message.')
        break
        print(message)
```

**Comment by felixdivo** [comment]
Hi @qdzpx123. The issue you files is hard to react to, since it is not clear what version of Python and this library you are using and what messages your are expecting. That's probably a reason why it was so silent here.

The code you provided should spit out a single message, if one appears on the bus. However, you should probably specify `channel="can0"` or `channel="can1"`. If the problem persists and is reproducible on a recent version, please comment again. You can install the most recent version with `pip install -e git+git://github.com/hardbyte/python-can.git@small-simplifications-serial#egg=python-can[serial]`.
